baseurl = "/"
languageCode = "en-us"
title = "A Hugo website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "My Gitee"
    url = "https://gitee.com/iaagbrx"
[[menu.main]]
    name = "My GitHub"
    url = "https://github.com/IAAG-BRX"
[[menu.main]]
    name = "More"
    url = "https://mooc1-3.chaoxing.com/mycourse/studentcourse?courseId=208815890&clazzid=17811461&ut=s&enc=1483a809c2925838c79e62e68bf0991b&cpi=107470798&openc=e585e41278e06d8004f544d63c12a67c"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

